name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to GHCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push image to GHCR
      - name: Build and push to GHCR
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/sense-voltage-scraper:latest .
          docker push ghcr.io/${{ github.repository_owner }}/sense-voltage-scraper:latest

      # Log in to DockerHub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Tag and push image to DockerHub
      - name: Tag and push to DockerHub
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/sense-voltage-scraper:latest ${{ secrets.DOCKERHUB_USERNAME }}/sense-voltage-scraper:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sense-voltage-scraper:latest
